import { create } from "zustand";
import { persist } from "zustand/middleware";
import { 
  User, Meeting, ActionItem, FollowUpDraft, PersonalEntry, 
  WorkStyleTone, MeetingParseState, ActionItemStatus
} from "./types";
import { v4 as uuidv4 } from "uuid";
import { addDays, format } from "date-fns";

// --- Mock Data Generator ---

const generateMockMeeting = (id: string, title: string, state: MeetingParseState): Meeting => ({
  id,
  title,
  date: new Date().toISOString(),
  attendees: [
    { id: "1", name: "Alice Johnson", email: "alice@example.com" },
    { id: "2", name: "Bob Smith", email: "bob@example.com" },
  ],
  rawNotes: "Alice will check the Q4 budget. Bob needs to update the slide deck by Friday. We agreed to launch on the 15th.",
  parseState: state,
  summary: state === 'parsed' || state === 'finalized' ? "Productive discussion on Q4 timeline and budget constraints." : undefined,
  decisions: state === 'parsed' || state === 'finalized' ? [{ id: "d1", text: "Launch date set for the 15th." }] : undefined,
  createdAt: new Date().toISOString(),
});

// --- Store State ---

interface AppState {
  user: User;
  meetings: Meeting[];
  actionItems: ActionItem[];
  drafts: FollowUpDraft[];
  personalEntries: PersonalEntry[];

  // Actions
  login: (email: string) => void;
  updateUser: (updates: Partial<User>) => void;
  
  addMeeting: (meeting: Partial<Meeting>) => string;
  updateMeeting: (id: string, updates: Partial<Meeting>) => void;
  deleteMeeting: (id: string) => void;
  
  extractMeeting: (id: string) => Promise<void>; // Simulates AI
  finalizeMeeting: (id: string) => void;
  
  updateActionItem: (id: string, updates: Partial<ActionItem>) => void;
  createActionItem: (item: Partial<ActionItem>) => void;
  
  generateDrafts: (meetingId: string) => void;
  updateDraft: (id: string, updates: Partial<FollowUpDraft>) => void;
}

export const useStore = create<AppState>()(
  persist(
    (set, get) => ({
      user: {
        id: "user-1",
        email: "demo@actionminutes.com",
        name: "Demo User",
        tone: "direct",
        timezone: "Europe/Dublin",
        aiEnabled: true,
        autoGenerateDrafts: true,
        enablePersonal: true,
        isAuthenticated: false,
      },
      meetings: [
        generateMockMeeting("m-1", "Product Sync", "finalized"),
        generateMockMeeting("m-2", "Marketing Kickoff", "draft"),
      ],
      actionItems: [
        {
          id: "a-1",
          meetingId: "m-1",
          text: "Update slide deck",
          ownerName: "Bob Smith",
          ownerEmail: "bob@example.com",
          dueDate: addDays(new Date(), 2).toISOString(),
          status: "open",
          confidenceOwner: 0.9,
          confidenceDueDate: 0.8,
          tags: ["slides"],
        },
        {
          id: "a-2",
          meetingId: "m-1",
          text: "Check Q4 budget",
          ownerName: "Alice Johnson",
          ownerEmail: "alice@example.com",
          dueDate: null,
          status: "needs_review",
          confidenceOwner: 0.9,
          confidenceDueDate: 0.2,
          tags: ["finance"],
        }
      ],
      drafts: [],
      personalEntries: [],

      login: (email) => set((state) => ({ 
        user: { ...state.user, email, isAuthenticated: true } 
      })),

      updateUser: (updates) => set((state) => ({
        user: { ...state.user, ...updates }
      })),

      addMeeting: (meeting) => {
        const id = uuidv4();
        const newMeeting: Meeting = {
          id,
          title: meeting.title || `Meeting — ${format(new Date(), "MMM d")}`,
          date: meeting.date || new Date().toISOString(),
          attendees: meeting.attendees || [],
          rawNotes: meeting.rawNotes || "",
          parseState: "draft",
          createdAt: new Date().toISOString(),
        };
        set((state) => ({ meetings: [newMeeting, ...state.meetings] }));
        return id;
      },

      updateMeeting: (id, updates) => set((state) => ({
        meetings: state.meetings.map((m) => m.id === id ? { ...m, ...updates } : m)
      })),
      
      deleteMeeting: (id) => set((state) => ({
        meetings: state.meetings.filter((m) => m.id !== id),
        actionItems: state.actionItems.filter((a) => a.meetingId !== id),
        drafts: state.drafts.filter((d) => d.meetingId !== id)
      })),

      extractMeeting: async (id) => {
        const meeting = get().meetings.find(m => m.id === id);
        if (!meeting) return;

        set((state) => ({
          meetings: state.meetings.map(m => m.id === id ? { ...m, parseState: "processing" } : m)
        }));

        // Simulate AI delay
        await new Promise(resolve => setTimeout(resolve, 2000));

        // Mock Extraction Logic
        const newActions: ActionItem[] = [
          {
            id: uuidv4(),
            meetingId: id,
            text: "Share the meeting notes with the team",
            ownerName: "Me",
            ownerEmail: get().user.email,
            dueDate: addDays(new Date(), 0).toISOString(),
            status: "needs_review",
            confidenceOwner: 0.95,
            confidenceDueDate: 0.6,
            tags: ["admin"],
          },
          {
            id: uuidv4(),
            meetingId: id,
            text: "Follow up with client regarding API access",
            ownerName: null,
            ownerEmail: null,
            dueDate: null,
            status: "needs_review",
            confidenceOwner: 0.1,
            confidenceDueDate: 0.1,
            tags: ["external"],
          }
        ];

        set((state) => ({
          meetings: state.meetings.map(m => m.id === id ? {
            ...m,
            parseState: "parsed",
            summary: "The team discussed the upcoming roadmap and identified key risks in the migration plan.",
            decisions: [
              { id: uuidv4(), text: "Proceed with Phase 1 migration on Monday." },
              { id: uuidv4(), text: "Use PostgreSQL for the new microservice." }
            ],
            risks: [
              { id: uuidv4(), text: "Data migration might take longer than expected.", severity: "medium" }
            ],
            clarifyingQuestions: [
              { id: uuidv4(), text: "Who is the primary owner for the frontend implementation?", options: ["Alice", "Bob"] }
            ]
          } : m),
          actionItems: [...state.actionItems, ...newActions]
        }));
        
        if (get().user.autoGenerateDrafts) {
            get().generateDrafts(id);
        }
      },

      finalizeMeeting: (id) => set((state) => ({
        meetings: state.meetings.map(m => m.id === id ? { ...m, parseState: "finalized" } : m)
      })),

      updateActionItem: (id, updates) => set((state) => ({
        actionItems: state.actionItems.map(a => a.id === id ? { ...a, ...updates } : a)
      })),
      
      createActionItem: (item) => set((state) => ({
        actionItems: [...state.actionItems, { ...item, id: uuidv4() } as ActionItem]
      })),

      generateDrafts: (meetingId) => {
         const meeting = get().meetings.find(m => m.id === meetingId);
         if (!meeting) return;

         const newDrafts: FollowUpDraft[] = [
             {
                 id: uuidv4(),
                 meetingId,
                 type: "general_summary",
                 recipientName: null,
                 recipientEmail: null,
                 subject: `Notes: ${meeting.title}`,
                 body: `Hi Team,\n\nHere is a summary of our meeting "${meeting.title}".\n\nSummary:\n${meeting.summary || "No summary"}\n\nDecisions:\n${meeting.decisions?.map(d => "- " + d.text).join("\n") || "None"}\n\nCheers,\nActionMinutes`,
                 tone: get().user.tone,
                 state: "generated",
                 updatedAt: new Date().toISOString()
             }
         ];
         
         set(state => ({
             drafts: [...state.drafts, ...newDrafts]
         }));
      },

      updateDraft: (id, updates) => set((state) => ({
        drafts: state.drafts.map(d => d.id === id ? { ...d, ...updates } : d)
      })),
    }),
    {
      name: "action-minutes-storage",
    }
  )
);
