import { create } from "zustand";
import { persist } from "zustand/middleware";

type Theme = "dark" | "light";

interface User {
  id: string;
  email: string;
  name: string;
  tone: string;
  timezone: string;
  defaultSignature?: string;
  aiEnabled: boolean;
  autoGenerateDrafts: boolean;
  enablePersonal: boolean;
  personalAiEnabled: boolean;
  allowImageStorage: boolean;
  hasCompletedOnboarding: boolean;
  hasCompletedTutorial: boolean;
  isAuthenticated: boolean;
  stripeCustomerId?: string;
  stripeSubscriptionId?: string;
  subscriptionStatus?: string;
  subscriptionPlan?: string;
}

interface AppState {
  user: User;
  theme: Theme;
  setUser: (user: User) => void;
  login: () => void;
  logout: () => void;
  updateUser: (updates: Partial<User>) => void;
  setTheme: (theme: Theme) => void;
  toggleTheme: () => void;
}

export const useStore = create<AppState>()(
  persist(
    (set, get) => ({
      user: {
        id: "",
        email: "",
        name: "",
        tone: "direct",
        timezone: "UTC",
        aiEnabled: true,
        autoGenerateDrafts: true,
        enablePersonal: false,
        personalAiEnabled: true,
        allowImageStorage: false,
        hasCompletedOnboarding: false,
        hasCompletedTutorial: false,
        isAuthenticated: false,
      },

      theme: "dark" as Theme,

      setUser: (user) => set({ user: { ...user, isAuthenticated: true } }),

      login: () => set((state) => ({ 
        user: { ...state.user, isAuthenticated: true } 
      })),

      logout: () => set({
        user: {
          id: "",
          email: "",
          name: "",
          tone: "direct",
          timezone: "UTC",
          aiEnabled: true,
          autoGenerateDrafts: true,
          enablePersonal: false,
          personalAiEnabled: true,
          allowImageStorage: false,
          hasCompletedOnboarding: false,
          hasCompletedTutorial: false,
          isAuthenticated: false,
        },
      }),

      updateUser: (updates) => set((state) => ({
        user: { ...state.user, ...updates }
      })),

      setTheme: (theme) => set({ theme }),

      toggleTheme: () => set((state) => ({ 
        theme: state.theme === "dark" ? "light" : "dark" 
      })),
    }),
    {
      name: "action-minutes-storage",
    }
  )
);
