import { z } from "zod";

// --- Domain Enums & Types ---

export type WorkStyleTone = "direct" | "friendly" | "formal";
export type MeetingParseState = "draft" | "processing" | "parsed" | "finalized" | "error";
export type ActionItemStatus = "needs_review" | "open" | "done" | "waiting";
export type DraftState = "generated" | "edited" | "exported" | "archived";
export type DraftType = "general_summary" | "to_individual";

// --- Models ---

export interface User {
  id: string;
  email: string;
  name: string;
  tone: WorkStyleTone;
  timezone: string;
  defaultSignature?: string;
  aiEnabled: boolean;
  autoGenerateDrafts: boolean;
  enablePersonal: boolean;
  personalAiEnabled: boolean;
  allowImageStorage: boolean;
  hasCompletedOnboarding: boolean;
  isAuthenticated: boolean; // Mock auth state
}

export interface Attendee {
  id: string;
  name: string;
  email?: string;
}

export interface Decision {
  id: string;
  text: string;
}

export interface Risk {
  id: string;
  text: string;
  severity: "low" | "medium" | "high";
}

export interface ClarifyingQuestion {
  id: string;
  text: string;
  options?: string[];
  answer?: string;
}

export interface ActionItem {
  id: string;
  meetingId: string;
  text: string;
  ownerName: string | null;
  ownerEmail: string | null;
  dueDate: string | null; // ISO string
  status: ActionItemStatus;
  confidenceOwner: number; // 0-1
  confidenceDueDate: number; // 0-1
  tags: string[];
  notes?: string;
  reminderAt?: string | null; // ISO string
}

export interface FollowUpDraft {
  id: string;
  meetingId: string;
  type: DraftType;
  recipientName: string | null;
  recipientEmail: string | null;
  subject: string;
  body: string;
  tone: WorkStyleTone;
  state: DraftState;
  updatedAt: string;
}

export interface Meeting {
  id: string;
  title: string;
  date: string; // ISO string
  startTime?: string;
  duration?: string;
  location?: string;
  attendees: Attendee[];
  rawNotes: string;
  parseState: MeetingParseState;
  
  // Extraction Results (Mocked inline for simplicity, or could be separate)
  summary?: string;
  decisions?: Decision[];
  risks?: Risk[];
  clarifyingQuestions?: ClarifyingQuestion[];
  qualityFlags?: string[];
  
  createdAt: string;
}

export interface PersonalEntry {
  id: string;
  date: string;
  rawText: string;
  summary?: string;
  top3?: string[];
  nextSteps?: string[];
}
