import { create } from 'zustand';

export interface User {
  id: string;
  email: string;
  name?: string;
  firstName?: string;
  lastName?: string;
  profileImageUrl?: string;
  timezone: string;
  aiEnabled: boolean;
  personalAiEnabled: boolean;
  autoGenerateDrafts: boolean;
  stripeCustomerId?: string;
  stripeSubscriptionId?: string;
  subscriptionStatus?: string;
  subscriptionPlan?: string;
  hasCompletedOnboarding: boolean;
  hasCompletedTutorial: boolean;
}

export interface CustomList {
  id: string;
  name: string;
  icon: string;
  color: string;
}

interface AppState {
  user: User | null;
  isLoading: boolean;
  theme: 'dark' | 'light';
  customLists: CustomList[];
  
  setUser: (user: User | null) => void;
  setLoading: (loading: boolean) => void;
  setTheme: (theme: 'dark' | 'light') => void;
  setCustomLists: (lists: CustomList[]) => void;
  logout: () => void;
}

export const useStore = create<AppState>((set) => ({
  user: null,
  isLoading: true,
  theme: 'dark',
  customLists: [],
  
  setUser: (user) => set({ user }),
  setLoading: (isLoading) => set({ isLoading }),
  setTheme: (theme) => set({ theme }),
  setCustomLists: (customLists) => set({ customLists }),
  logout: () => set({ user: null }),
}));
