import { useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useStore } from "@/lib/store";
import type { User } from "@shared/schema";

async function fetchUser(): Promise<User | null> {
  const response = await fetch("/api/auth/user", {
    credentials: "include",
  });

  if (response.status === 401) {
    return null;
  }

  if (!response.ok) {
    throw new Error(`${response.status}: ${response.statusText}`);
  }

  return response.json();
}

async function logoutFn(): Promise<void> {
  window.location.href = "/api/logout";
}

export function useAuth() {
  const queryClient = useQueryClient();
  const { setUser, logout: storeLogout } = useStore();
  
  const { data: user, isLoading } = useQuery<User | null>({
    queryKey: ["/api/auth/user"],
    queryFn: fetchUser,
    retry: false,
    staleTime: 1000 * 60 * 5,
  });

  useEffect(() => {
    if (user) {
      setUser({
        id: user.id,
        email: user.email || "",
        name: user.name || user.firstName || "User",
        tone: user.tone || "direct",
        timezone: user.timezone || "UTC",
        defaultSignature: user.defaultSignature || undefined,
        aiEnabled: user.aiEnabled ?? true,
        autoGenerateDrafts: user.autoGenerateDrafts ?? true,
        enablePersonal: user.enablePersonal ?? true,
        personalAiEnabled: user.personalAiEnabled ?? true,
        allowImageStorage: user.allowImageStorage ?? false,
        isAuthenticated: true,
      });
    }
  }, [user, setUser]);

  const logoutMutation = useMutation({
    mutationFn: logoutFn,
    onSuccess: () => {
      queryClient.setQueryData(["/api/auth/user"], null);
      storeLogout();
    },
  });

  return {
    user,
    isLoading,
    isAuthenticated: !!user,
    logout: logoutMutation.mutate,
    isLoggingOut: logoutMutation.isPending,
  };
}
