import { useEffect, useRef } from "react";
import { useUser, useClerk } from "@clerk/clerk-react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useStore } from "@/lib/store";
import type { User } from "@shared/schema";

async function syncUserToBackend(
  clerkUser: {
    id: string;
    emailAddresses: { emailAddress: string }[];
    firstName: string | null;
    lastName: string | null;
  },
  getToken: () => Promise<string | null>
): Promise<User> {
  const email = clerkUser.emailAddresses[0]?.emailAddress || "";
  const name = [clerkUser.firstName, clerkUser.lastName].filter(Boolean).join(" ") || "User";
  
  const token = await getToken();
  if (!token) {
    throw new Error("No token available");
  }
  
  const response = await fetch("/api/auth/clerk-sync", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${token}`,
    },
    credentials: "include",
    body: JSON.stringify({
      clerkId: clerkUser.id,
      email,
      name,
    }),
  });

  if (!response.ok) {
    throw new Error("Failed to sync user");
  }

  return response.json();
}

async function fetchUser(): Promise<User | null> {
  const response = await fetch("/api/auth/user", {
    credentials: "include",
  });

  if (response.status === 401) {
    return null;
  }

  if (!response.ok) {
    throw new Error(`${response.status}: ${response.statusText}`);
  }

  return response.json();
}

async function logoutBackend(): Promise<void> {
  await fetch("/api/auth/logout", {
    method: "POST",
    credentials: "include",
  });
}

export function useAuth() {
  const queryClient = useQueryClient();
  const { setUser, logout: storeLogout } = useStore();
  const { user: clerkUser, isLoaded: clerkLoaded, isSignedIn } = useUser();
  const { signOut, session } = useClerk();
  
  const { data: user, isLoading: dbUserLoading, refetch } = useQuery<User | null>({
    queryKey: ["/api/auth/user"],
    queryFn: fetchUser,
    retry: false,
    staleTime: 1000 * 60 * 5,
    enabled: clerkLoaded && isSignedIn,
  });

  const syncAttemptedRef = useRef(false);
  
  useEffect(() => {
    if (clerkLoaded && isSignedIn && clerkUser && !user && session && !syncAttemptedRef.current) {
      syncAttemptedRef.current = true;
      
      const attemptSync = async (retries = 3) => {
        for (let i = 0; i < retries; i++) {
          try {
            const getToken = () => session.getToken();
            const syncedUser = await syncUserToBackend(clerkUser, getToken);
            queryClient.setQueryData(["/api/auth/user"], syncedUser);
            return;
          } catch (error) {
            if (i < retries - 1) {
              await new Promise(resolve => setTimeout(resolve, 500 * (i + 1)));
            } else {
              console.error("Failed to sync user after retries:", error);
            }
          }
        }
      };
      
      attemptSync();
    }
    
    if (!isSignedIn) {
      syncAttemptedRef.current = false;
    }
  }, [clerkLoaded, isSignedIn, clerkUser, user, queryClient, session]);

  useEffect(() => {
    if (clerkLoaded && !isSignedIn) {
      queryClient.setQueryData(["/api/auth/user"], null);
      storeLogout();
    }
  }, [clerkLoaded, isSignedIn, queryClient, storeLogout]);

  useEffect(() => {
    if (isSignedIn && user) {
      setUser({
        id: user.id,
        email: user.email || "",
        name: user.name || user.firstName || "User",
        tone: user.tone || "direct",
        timezone: user.timezone || "UTC",
        defaultSignature: user.defaultSignature || undefined,
        aiEnabled: user.aiEnabled ?? true,
        autoGenerateDrafts: user.autoGenerateDrafts ?? true,
        enablePersonal: user.enablePersonal ?? false,
        personalAiEnabled: user.personalAiEnabled ?? true,
        allowImageStorage: user.allowImageStorage ?? false,
        hasCompletedOnboarding: user.hasCompletedOnboarding ?? false,
        hasCompletedTutorial: user.hasCompletedTutorial ?? false,
        isAuthenticated: true,
      });
    }
  }, [isSignedIn, user, setUser]);

  const isLoading = !clerkLoaded || (isSignedIn && dbUserLoading);

  const logout = async () => {
    // Clear local state first
    storeLogout();
    queryClient.clear();
    
    // Then logout from backend and Clerk
    await logoutBackend();
    await signOut();
  };

  return {
    user: isSignedIn ? user : null,
    isLoading,
    isAuthenticated: !!isSignedIn && !!user,
    logout,
    refetch,
  };
}
