import { useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useStore } from "@/lib/store";
import type { User } from "@shared/schema";

async function fetchUser(): Promise<User | null> {
  const response = await fetch("/api/auth/user", {
    credentials: "include",
  });

  if (response.status === 401) {
    return null;
  }

  if (!response.ok) {
    throw new Error(`${response.status}: ${response.statusText}`);
  }

  return response.json();
}

async function loginFn(email: string, password: string): Promise<User> {
  const response = await fetch("/api/auth/login", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    credentials: "include",
    body: JSON.stringify({ email, password }),
  });

  if (!response.ok) {
    const data = await response.json();
    throw new Error(data.error || "Login failed");
  }

  return response.json();
}

async function registerFn(email: string, password: string, name?: string): Promise<User> {
  const response = await fetch("/api/auth/register", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    credentials: "include",
    body: JSON.stringify({ email, password, name }),
  });

  if (!response.ok) {
    const data = await response.json();
    throw new Error(data.error || "Registration failed");
  }

  return response.json();
}

async function logoutFn(): Promise<void> {
  await fetch("/api/auth/logout", {
    method: "POST",
    credentials: "include",
  });
}

export function useAuth() {
  const queryClient = useQueryClient();
  const { setUser, logout: storeLogout } = useStore();
  
  const { data: user, isLoading } = useQuery<User | null>({
    queryKey: ["/api/auth/user"],
    queryFn: fetchUser,
    retry: false,
    staleTime: 1000 * 60 * 5,
  });

  useEffect(() => {
    if (user) {
      setUser({
        id: user.id,
        email: user.email || "",
        name: user.name || user.firstName || "User",
        tone: user.tone || "direct",
        timezone: user.timezone || "UTC",
        defaultSignature: user.defaultSignature || undefined,
        aiEnabled: user.aiEnabled ?? true,
        autoGenerateDrafts: user.autoGenerateDrafts ?? true,
        enablePersonal: user.enablePersonal ?? true,
        personalAiEnabled: user.personalAiEnabled ?? true,
        allowImageStorage: user.allowImageStorage ?? false,
        isAuthenticated: true,
      });
    }
  }, [user, setUser]);

  const login = async (email: string, password: string) => {
    const user = await loginFn(email, password);
    queryClient.setQueryData(["/api/auth/user"], user);
    return user;
  };

  const register = async (email: string, password: string, name?: string) => {
    const user = await registerFn(email, password, name);
    queryClient.setQueryData(["/api/auth/user"], user);
    return user;
  };

  const logout = async () => {
    await logoutFn();
    queryClient.setQueryData(["/api/auth/user"], null);
    storeLogout();
  };

  return {
    user,
    isLoading,
    isAuthenticated: !!user,
    login,
    register,
    logout,
  };
}
