import { useState } from "react";
import { useStore } from "@/lib/store";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { WorkStyleTone } from "@/lib/types";
import { ArrowRight, Check } from "lucide-react";

export default function OnboardingPage() {
  const { updateUser } = useStore();
  const [, setLocation] = useLocation();
  const [step, setStep] = useState(1);
  const [tone, setTone] = useState<WorkStyleTone>("direct");
  const [autoDraft, setAutoDraft] = useState(true);

  const handleFinish = () => {
    updateUser({ 
      tone, 
      autoGenerateDrafts: autoDraft 
    });
    setLocation("/inbox");
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4 bg-muted/30">
      <Card className="w-full max-w-lg border-none shadow-xl shadow-black/5">
        <CardHeader>
          <div className="flex justify-between items-center mb-2">
             <div className="flex space-x-1">
               <div className={`h-1 w-8 rounded-full ${step >= 1 ? 'bg-primary' : 'bg-muted'}`} />
               <div className={`h-1 w-8 rounded-full ${step >= 2 ? 'bg-primary' : 'bg-muted'}`} />
               <div className={`h-1 w-8 rounded-full ${step >= 3 ? 'bg-primary' : 'bg-muted'}`} />
             </div>
             <span className="text-sm text-muted-foreground">Step {step} of 3</span>
          </div>
          <CardTitle className="text-2xl">
            {step === 1 && "Set your work style"}
            {step === 2 && "Default behavior"}
            {step === 3 && "Personal (optional)"}
          </CardTitle>
          <CardDescription>
            {step === 1 && "How should your AI assistant write drafts?"}
            {step === 2 && "Configure automation settings"}
            {step === 3 && "Separate work from personal brain-dumps"}
          </CardDescription>
        </CardHeader>

        <CardContent className="space-y-6 pt-4">
          {step === 1 && (
            <RadioGroup value={tone} onValueChange={(v) => setTone(v as WorkStyleTone)} className="space-y-3">
              <div className={`flex items-start space-x-3 p-4 rounded-lg border-2 cursor-pointer transition-all ${tone === 'direct' ? 'border-primary bg-primary/5' : 'border-transparent bg-secondary'}`} onClick={() => setTone('direct')}>
                <RadioGroupItem value="direct" id="direct" className="mt-1" />
                <div>
                  <Label htmlFor="direct" className="font-semibold text-base cursor-pointer">Direct</Label>
                  <p className="text-sm text-muted-foreground mt-1">Short, clear, no fluff. Gets straight to the point.</p>
                </div>
              </div>
              <div className={`flex items-start space-x-3 p-4 rounded-lg border-2 cursor-pointer transition-all ${tone === 'friendly' ? 'border-primary bg-primary/5' : 'border-transparent bg-secondary'}`} onClick={() => setTone('friendly')}>
                <RadioGroupItem value="friendly" id="friendly" className="mt-1" />
                <div>
                  <Label htmlFor="friendly" className="font-semibold text-base cursor-pointer">Friendly</Label>
                  <p className="text-sm text-muted-foreground mt-1">Warm but efficient. Good for client emails.</p>
                </div>
              </div>
              <div className={`flex items-start space-x-3 p-4 rounded-lg border-2 cursor-pointer transition-all ${tone === 'formal' ? 'border-primary bg-primary/5' : 'border-transparent bg-secondary'}`} onClick={() => setTone('formal')}>
                <RadioGroupItem value="formal" id="formal" className="mt-1" />
                <div>
                  <Label htmlFor="formal" className="font-semibold text-base cursor-pointer">Formal</Label>
                  <p className="text-sm text-muted-foreground mt-1">Traditional wording. Professional and polite.</p>
                </div>
              </div>
            </RadioGroup>
          )}

          {step === 2 && (
            <div className="space-y-6">
              <div className="flex items-center justify-between space-x-4">
                <div className="space-y-1">
                  <Label className="text-base">Auto-generate drafts</Label>
                  <p className="text-sm text-muted-foreground">Create follow-up emails immediately after extraction</p>
                </div>
                <Switch checked={autoDraft} onCheckedChange={setAutoDraft} />
              </div>
              
              <div className="space-y-2">
                 <Label>Default Timezone</Label>
                 <Select defaultValue="dublin">
                   <SelectTrigger>
                     <SelectValue placeholder="Select timezone" />
                   </SelectTrigger>
                   <SelectContent>
                     <SelectItem value="dublin">Europe/Dublin (GMT+0)</SelectItem>
                     <SelectItem value="ny">America/New_York (EST)</SelectItem>
                     <SelectItem value="sf">America/Los_Angeles (PST)</SelectItem>
                   </SelectContent>
                 </Select>
              </div>
            </div>
          )}

          {step === 3 && (
            <div className="space-y-4">
              <div className="bg-secondary/50 p-6 rounded-lg text-center space-y-4">
                <div className="mx-auto h-12 w-12 bg-primary/10 rounded-full flex items-center justify-center">
                   <span className="text-xl">🧠</span>
                </div>
                <div className="space-y-2">
                  <h3 className="font-medium">Personal Mode</h3>
                  <p className="text-muted-foreground text-sm">
                    Personal is a lightweight brain-dump + Top 3 priorities. 
                    Work stays the focus, but sometimes you need to clear your head.
                  </p>
                </div>
                <Button variant="outline" className="w-full">Enable Personal Tab</Button>
              </div>
            </div>
          )}
        </CardContent>

        <CardFooter className="flex justify-between">
          <Button variant="ghost" onClick={() => setStep(s => Math.max(1, s - 1))} disabled={step === 1}>
            Back
          </Button>
          <Button onClick={() => step < 3 ? setStep(s => s + 1) : handleFinish()} className="w-32">
            {step < 3 ? (
              <>Next <ArrowRight className="ml-2 h-4 w-4" /></>
            ) : (
              <>Finish <Check className="ml-2 h-4 w-4" /></>
            )}
          </Button>
        </CardFooter>
      </Card>
    </div>
  );
}
