import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useStore } from "@/lib/store";
import { useUpdateUser } from "@/lib/hooks";
import { Link } from "wouter";
import { ExternalLink, Settings2, Plug, Calendar, Sparkles, Users } from "lucide-react";
import SettingsIntegrationsPage from "./settings-integrations";
import SettingsExportsPage from "./settings-exports";
import SettingsAuditPage from "./settings-audit";
import WorkspaceSettingsPage from "./workspace-settings";

export default function SettingsPage() {
  const { user, updateUser: updateLocalUser, currentWorkspaceId } = useStore();
  const updateUser = useUpdateUser();

  const handleToggle = (field: string, value: boolean) => {
    updateLocalUser({ [field]: value });
    updateUser.mutate({ [field]: value });
  };

  const handleToneChange = (tone: string) => {
    updateLocalUser({ tone });
    updateUser.mutate({ tone });
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <h1 className="text-3xl font-bold tracking-tight text-slate-800">Settings</h1>

      <Tabs defaultValue="preferences" className="space-y-6">
        <TabsList className="bg-stone-100 rounded-2xl p-1">
          <TabsTrigger value="preferences" className="rounded-xl data-[state=active]:bg-white data-[state=active]:shadow-sm" data-testid="tab-preferences">
            <Settings2 className="h-4 w-4 mr-2" />
            Preferences
          </TabsTrigger>
          <TabsTrigger value="integrations" className="rounded-xl data-[state=active]:bg-white data-[state=active]:shadow-sm" data-testid="tab-integrations">
            <Plug className="h-4 w-4 mr-2" />
            Integrations
          </TabsTrigger>
          <TabsTrigger value="exports" className="rounded-xl data-[state=active]:bg-white data-[state=active]:shadow-sm" data-testid="tab-exports">
            <Calendar className="h-4 w-4 mr-2" />
            Exports
          </TabsTrigger>
          <TabsTrigger value="ai-audit" className="rounded-xl data-[state=active]:bg-white data-[state=active]:shadow-sm" data-testid="tab-ai-audit">
            <Sparkles className="h-4 w-4 mr-2" />
            AI Audit
          </TabsTrigger>
          {currentWorkspaceId && (
            <TabsTrigger value="workspace" className="rounded-xl data-[state=active]:bg-white data-[state=active]:shadow-sm" data-testid="tab-workspace">
              <Users className="h-4 w-4 mr-2" />
              Workspace
            </TabsTrigger>
          )}
        </TabsList>

        <TabsContent value="preferences" className="space-y-6">
          <Card className="bg-white border-stone-200 rounded-3xl">
            <CardHeader>
              <CardTitle className="text-slate-800">AI Preferences</CardTitle>
              <CardDescription className="text-stone-500">Control how the AI processes your meetings.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
               <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label className="text-base text-slate-700">Enable AI Extraction</Label>
                    <p className="text-sm text-stone-500">Process notes to find actions automatically.</p>
                  </div>
                  <Switch 
                    checked={user.aiEnabled} 
                    onCheckedChange={(c) => handleToggle('aiEnabled', c)}
                    data-testid="switch-ai-enabled"
                  />
               </div>
               <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label className="text-base text-slate-700">Auto-generate Drafts</Label>
                    <p className="text-sm text-stone-500">Create follow-up emails immediately.</p>
                  </div>
                  <Switch 
                    checked={user.autoGenerateDrafts} 
                    onCheckedChange={(c) => handleToggle('autoGenerateDrafts', c)}
                    data-testid="switch-auto-drafts"
                  />
               </div>
            </CardContent>
          </Card>

          <Card className="bg-white border-stone-200 rounded-3xl">
            <CardHeader>
              <CardTitle className="text-slate-800">Work Style</CardTitle>
            </CardHeader>
            <CardContent>
               <div className="grid gap-2">
                  <Label className="text-slate-700">Tone</Label>
                  <div className="flex gap-2">
                    {['direct', 'friendly', 'formal'].map((t) => (
                      <Button 
                        key={t}
                        variant={user.tone === t ? 'default' : 'outline'}
                        onClick={() => handleToneChange(t)}
                        className={`capitalize rounded-2xl ${user.tone === t ? 'bg-teal-500 hover:bg-teal-600' : 'border-stone-300'}`}
                        data-testid={`button-tone-${t}`}
                      >
                        {t}
                      </Button>
                    ))}
                  </div>
               </div>
            </CardContent>
          </Card>
          
          <div className="p-4 bg-amber-50 text-amber-800 rounded-2xl text-sm border border-amber-200">
            <strong>Note:</strong> Your notes will be processed by an AI service to generate outputs. You can disable AI anytime.
          </div>

          <div className="pt-4 flex justify-end">
             <Link href="/blueprint">
               <Button variant="link" className="text-stone-500">
                 View Blueprint <ExternalLink className="ml-1 h-3 w-3" />
               </Button>
             </Link>
          </div>
        </TabsContent>

        <TabsContent value="integrations">
          <SettingsIntegrationsPage />
        </TabsContent>

        <TabsContent value="exports">
          <SettingsExportsPage />
        </TabsContent>

        <TabsContent value="ai-audit">
          <SettingsAuditPage />
        </TabsContent>

        {currentWorkspaceId && (
          <TabsContent value="workspace">
            <WorkspaceSettingsPage workspaceId={currentWorkspaceId} />
          </TabsContent>
        )}
      </Tabs>
    </div>
  );
}
