import { useState, type ReactNode } from "react";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { useStore } from "@/lib/store";
import { useUpdateUser } from "@/lib/hooks";
import { Link } from "wouter";
import { 
  GearSix, Plug, CalendarBlank, Sparkle, UsersThree, ChatCircle, ShieldCheck, 
  User, BookOpen, Clock, FileText, Scales, CaretDown, CaretRight, Info, Lifebuoy 
} from "@phosphor-icons/react";
import SettingsIntegrationsPage from "./settings-integrations";
import SettingsExportsPage from "./settings-exports";
import WorkspaceSettingsPage from "./workspace-settings";
import SettingsPrivacyPage from "./settings-privacy";
import SettingsTermsPage from "./settings-terms";
import { FeedbackModal } from "@/components/feedback-modal";
import { useRestartTutorial } from "@/components/tutorial";
import { cn } from "@/lib/utils";

const ADMIN_EMAIL = "tomi.vida@gmail.com";

interface ExpandableSectionProps {
  title: string;
  icon: ReactNode;
  defaultOpen?: boolean;
  children: ReactNode;
  testId?: string;
}

function ExpandableSection({ title, icon, defaultOpen = false, children, testId }: ExpandableSectionProps) {
  const [isOpen, setIsOpen] = useState(defaultOpen);
  
  return (
    <Collapsible open={isOpen} onOpenChange={setIsOpen}>
      <Card className="bg-white border-gray-200 rounded-xl overflow-hidden">
        <CollapsibleTrigger asChild>
          <button
            className="w-full flex items-center justify-between px-4 py-4 md:px-6 hover:bg-gray-50 transition-colors"
            data-testid={testId}
          >
            <div className="flex items-center gap-3">
              {icon}
              <span className="text-lg font-semibold text-slate-800">{title}</span>
            </div>
            {isOpen ? (
              <CaretDown className="h-5 w-5 text-gray-400" weight="duotone" />
            ) : (
              <CaretRight className="h-5 w-5 text-gray-400" weight="duotone" />
            )}
          </button>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="px-4 pb-4 md:px-6 md:pb-6 border-t border-gray-100 pt-4">
            {children}
          </div>
        </CollapsibleContent>
      </Card>
    </Collapsible>
  );
}

export default function SettingsPage() {
  const { user, updateUser: updateLocalUser, currentWorkspaceId } = useStore();
  const updateUser = useUpdateUser();
  const restartTutorial = useRestartTutorial();
  const [feedbackOpen, setFeedbackOpen] = useState(false);

  const isAdmin = user.email === ADMIN_EMAIL;

  const handleToggle = (field: string, value: boolean) => {
    updateLocalUser({ [field]: value });
    updateUser.mutate({ [field]: value });
  };

  const handleToneChange = (tone: string) => {
    updateLocalUser({ tone });
    updateUser.mutate({ tone });
  };

  return (
    <div className="space-y-4 md:space-y-5">
      <h1 className="text-2xl md:text-3xl font-bold tracking-tight text-slate-800">Settings</h1>

      {/* AI Preferences Section */}
      <ExpandableSection
        title="AI Preferences"
        icon={<Sparkle className="h-5 w-5 text-indigo-500" weight="duotone" />}
        testId="section-ai-preferences"
      >
        <div className="space-y-6">
          {/* AI Settings */}
          <div className="space-y-4">
            <h3 className="font-medium text-slate-700">AI Extraction</h3>
            <div className="space-y-4">
              <div className="flex items-start justify-between gap-4 py-2">
                <div className="space-y-1 flex-1">
                  <Label className="text-base text-slate-700">Enable AI Extraction</Label>
                  <p className="text-sm text-gray-500">Process notes to find actions automatically.</p>
                </div>
                <Switch 
                  checked={user.aiEnabled} 
                  onCheckedChange={(c) => handleToggle('aiEnabled', c)}
                  className="mt-1 shrink-0"
                  data-testid="switch-ai-enabled"
                />
              </div>
              <div className="flex items-start justify-between gap-4 py-2">
                <div className="space-y-1 flex-1">
                  <Label className="text-base text-slate-700">Auto-generate Drafts</Label>
                  <p className="text-sm text-gray-500">Create follow-up emails immediately.</p>
                </div>
                <Switch 
                  checked={user.autoGenerateDrafts} 
                  onCheckedChange={(c) => handleToggle('autoGenerateDrafts', c)}
                  className="mt-1 shrink-0"
                  data-testid="switch-auto-drafts"
                />
              </div>
              <div className="flex items-start justify-between gap-4 py-2">
                <div className="space-y-1 flex-1">
                  <Label className="text-base text-slate-700">Personal AI</Label>
                  <p className="text-sm text-gray-500">Enable AI suggestions and summaries in your private journal.</p>
                </div>
                <Switch 
                  checked={user.personalAiEnabled !== false} 
                  onCheckedChange={(c) => handleToggle('personalAiEnabled', c)}
                  className="mt-1 shrink-0"
                  data-testid="switch-personal-ai-enabled"
                />
              </div>
            </div>
          </div>

          {/* Work Style */}
          <div className="space-y-4 pt-4 border-t border-gray-100">
            <h3 className="font-medium text-slate-700">Work Style</h3>
            <div className="space-y-3">
              <Label className="text-base text-slate-700">Tone</Label>
              <div className="flex flex-wrap gap-2">
                {['direct', 'friendly', 'formal'].map((t) => (
                  <Button 
                    key={t}
                    variant={user.tone === t ? 'default' : 'outline'}
                    onClick={() => handleToneChange(t)}
                    className={cn(
                      "capitalize rounded-xl h-11 px-5 flex-1 sm:flex-none",
                      user.tone === t ? 'btn-gradient text-white font-semibold' : 'border-gray-300'
                    )}
                    data-testid={`button-tone-${t}`}
                  >
                    {t}
                  </Button>
                ))}
              </div>
            </div>
          </div>

          <div className="p-4 bg-amber-50 text-amber-800 rounded-xl text-sm border border-amber-200">
            <strong>Note:</strong> Your notes will be processed by an AI service to generate outputs. You can disable AI anytime.
          </div>
        </div>
      </ExpandableSection>

      {/* Integrations Section */}
      <ExpandableSection
        title="Integrations"
        icon={<Plug className="h-5 w-5 text-green-500" weight="duotone" />}
        testId="section-integrations"
      >
        <SettingsIntegrationsPage />
      </ExpandableSection>

      {/* Exports Section */}
      <ExpandableSection
        title="Exports"
        icon={<CalendarBlank className="h-5 w-5 text-blue-500" weight="duotone" />}
        testId="section-exports"
      >
        <SettingsExportsPage />
      </ExpandableSection>

      {/* Workspace Section - only show if in a workspace */}
      {currentWorkspaceId && (
        <ExpandableSection
          title="Workspace"
          icon={<UsersThree className="h-5 w-5 text-purple-500" weight="duotone" />}
          testId="section-workspace"
        >
          <WorkspaceSettingsPage workspaceId={currentWorkspaceId} />
        </ExpandableSection>
      )}

      {/* Personal Section */}
      <ExpandableSection
        title="Personal"
        icon={<User className="h-5 w-5 text-pink-500" weight="duotone" />}
        testId="section-personal"
      >
        <div className="space-y-4">
          <div className="p-4 bg-indigo-50 rounded-xl text-sm border border-indigo-200">
            <h3 className="font-semibold text-indigo-800 mb-1">Your Personal Space</h3>
            <p className="text-indigo-700">These features are private to you. No one else can see your personal meetings, journal entries, or reminders.</p>
          </div>

          <div className="space-y-3">
            <Link href="/journal">
              <Button variant="outline" className="w-full justify-start h-12 rounded-xl border-gray-200" data-testid="link-journal">
                <BookOpen className="h-4 w-4 mr-3 text-purple-500" weight="duotone" />
                Open Journal
              </Button>
            </Link>
            <Link href="/reminders">
              <Button variant="outline" className="w-full justify-start h-12 rounded-xl border-gray-200" data-testid="link-reminders">
                <Clock className="h-4 w-4 mr-3 text-indigo-500" weight="duotone" />
                Open Reminders
              </Button>
            </Link>
          </div>

          <div className="p-4 bg-gray-50 rounded-xl text-sm text-gray-600 border border-gray-200">
            <strong>Personal vs Team:</strong> Personal meetings are only visible to you. When you join or create a workspace, you can save meetings to that workspace for team visibility.
          </div>
        </div>
      </ExpandableSection>

      {/* Support & Legal Section */}
      <ExpandableSection
        title="Support & Legal"
        icon={<ChatCircle className="h-5 w-5 text-orange-500" weight="duotone" />}
        testId="section-support"
      >
        <div className="space-y-4">
          {/* About ActionMinutes */}
          <div className="space-y-3">
            <h3 className="font-medium text-slate-700 flex items-center gap-2">
              <Info className="h-4 w-4 text-indigo-500" weight="duotone" />
              About ActionMinutes
            </h3>
            <div className="p-4 bg-gradient-to-br from-indigo-50 to-purple-50 rounded-xl border border-indigo-100">
              <p className="text-sm text-slate-700 leading-relaxed">
                ActionMinutes transforms your messy meeting notes into actionable outputs. 
                Simply capture your notes, and we'll extract clear action items with owners and due dates, 
                key decisions, and ready-to-send follow-up emails — all in under 60 seconds.
              </p>
              <p className="text-xs text-slate-500 mt-3">
                Minutes → Actions → Follow-ups
              </p>
            </div>
          </div>

          {/* Privacy Settings */}
          <div className="space-y-3 pt-4 border-t border-gray-100">
            <h3 className="font-medium text-slate-700 flex items-center gap-2">
              <ShieldCheck className="h-4 w-4 text-indigo-500" weight="duotone" />
              Privacy Settings
            </h3>
            <div className="flex items-start justify-between gap-4 py-2 pl-2">
              <div className="space-y-1 flex-1">
                <Label className="text-base text-slate-700">Allow storing uploaded images</Label>
                <p className="text-sm text-gray-500">When off, uploaded photos of handwritten notes are processed and immediately deleted.</p>
                <p className="text-xs text-amber-600">Images can contain sensitive information.</p>
              </div>
              <Switch 
                checked={user.allowImageStorage ?? false} 
                onCheckedChange={(c) => handleToggle('allowImageStorage', c)}
                className="mt-1 shrink-0"
                data-testid="switch-allow-image-storage"
              />
            </div>
          </div>

          {/* Legal Links */}
          <div className="space-y-3 pt-4 border-t border-gray-100">
            <h3 className="font-medium text-slate-700">Legal</h3>
            <div className="space-y-2">
              <Link href="/privacy-policy">
                <Button variant="outline" className="w-full justify-start h-11 rounded-xl border-gray-200 text-slate-700" data-testid="link-privacy-policy">
                  <ShieldCheck className="h-4 w-4 mr-3 text-gray-500" weight="duotone" />
                  Privacy Policy
                </Button>
              </Link>
              <Link href="/terms">
                <Button variant="outline" className="w-full justify-start h-11 rounded-xl border-gray-200 text-slate-700" data-testid="link-terms">
                  <Scales className="h-4 w-4 mr-3 text-gray-500" weight="duotone" />
                  Terms of Service
                </Button>
              </Link>
            </div>
          </div>

          {/* Help & Feedback */}
          <div className="space-y-3 pt-4 border-t border-gray-100">
            <h3 className="font-medium text-slate-700">Help & Feedback</h3>
            <Button
              variant="outline"
              onClick={restartTutorial}
              className="w-full justify-start h-11 rounded-xl border-gray-200 text-slate-700"
              data-testid="button-restart-tutorial"
            >
              <Lifebuoy className="h-4 w-4 mr-3 text-purple-500" weight="duotone" />
              Take a Tour
            </Button>
            <Button
              variant="outline"
              onClick={() => setFeedbackOpen(true)}
              className="w-full justify-start h-11 rounded-xl border-gray-200 text-slate-700"
              data-testid="button-send-feedback"
            >
              <ChatCircle className="h-4 w-4 mr-3 text-indigo-500" weight="duotone" />
              Send Feedback
            </Button>
            
            {/* Admin only - View Feedback */}
            {isAdmin && (
              <Link href="/admin/feedback">
                <Button
                  variant="outline"
                  className="w-full justify-start h-11 rounded-xl border-gray-200 text-slate-700"
                  data-testid="button-admin-feedback"
                >
                  <ShieldCheck className="h-4 w-4 mr-3 text-purple-500" weight="duotone" />
                  Admin: View Feedback
                </Button>
              </Link>
            )}
          </div>
        </div>
      </ExpandableSection>

      {/* Version Number */}
      <div className="text-center py-4">
        <p className="text-xs text-gray-400">ActionMinutes v1.0.0</p>
      </div>

      <FeedbackModal open={feedbackOpen} onOpenChange={setFeedbackOpen} />
    </div>
  );
}
