import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card";
import { useStore } from "@/lib/store";
import { Link } from "wouter";
import { ExternalLink } from "lucide-react";

export default function SettingsPage() {
  const { user, updateUser } = useStore();

  return (
    <div className="max-w-2xl mx-auto space-y-8">
      <h1 className="text-3xl font-bold tracking-tight">Settings</h1>

      <div className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>AI Preferences</CardTitle>
            <CardDescription>Control how the AI processes your meetings.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
             <div className="flex items-center justify-between">
                <div className="space-y-0.5">
                  <Label className="text-base">Enable AI Extraction</Label>
                  <p className="text-sm text-muted-foreground">Process notes to find actions automatically.</p>
                </div>
                <Switch checked={user.aiEnabled} onCheckedChange={(c) => updateUser({ aiEnabled: c })} />
             </div>
             <div className="flex items-center justify-between">
                <div className="space-y-0.5">
                  <Label className="text-base">Auto-generate Drafts</Label>
                  <p className="text-sm text-muted-foreground">Create follow-up emails immediately.</p>
                </div>
                <Switch checked={user.autoGenerateDrafts} onCheckedChange={(c) => updateUser({ autoGenerateDrafts: c })} />
             </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Work Style</CardTitle>
          </CardHeader>
          <CardContent>
             <div className="grid gap-2">
                <Label>Tone</Label>
                <div className="flex gap-2">
                  {['direct', 'friendly', 'formal'].map((t) => (
                    <Button 
                      key={t}
                      variant={user.tone === t ? 'default' : 'outline'}
                      onClick={() => updateUser({ tone: t as any })}
                      className="capitalize"
                    >
                      {t}
                    </Button>
                  ))}
                </div>
             </div>
          </CardContent>
        </Card>
        
        <div className="p-4 bg-amber-50 dark:bg-amber-900/20 text-amber-800 dark:text-amber-200 rounded-lg text-sm">
          <strong>Note:</strong> Your notes will be processed by an AI service to generate outputs. You can disable AI anytime.
        </div>

        <div className="pt-4 flex justify-end">
           <Link href="/blueprint">
             <Button variant="link" className="text-muted-foreground">
               View Blueprint <ExternalLink className="ml-1 h-3 w-3" />
             </Button>
           </Link>
        </div>
      </div>
    </div>
  );
}
