import { sql } from "drizzle-orm";
import { index, jsonb, pgTable, timestamp, varchar, text, boolean } from "drizzle-orm/pg-core";

// Session storage table.
// (IMPORTANT) This table is mandatory for Replit Auth, don't drop it.
export const sessions = pgTable(
  "sessions",
  {
    sid: varchar("sid").primaryKey(),
    sess: jsonb("sess").notNull(),
    expire: timestamp("expire").notNull(),
  },
  (table) => [index("IDX_session_expire").on(table.expire)]
);

// User storage table - combines Replit Auth fields with app-specific fields
// (IMPORTANT) This table is mandatory for Replit Auth, don't drop it.
export const users = pgTable("users", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  email: text("email").unique(),
  password: text("password"),
  firstName: varchar("first_name"),
  lastName: varchar("last_name"),
  profileImageUrl: varchar("profile_image_url"),
  // App-specific fields
  name: text("name"),
  tone: text("tone").notNull().default('direct'),
  timezone: text("timezone").notNull().default('UTC'),
  defaultSignature: text("default_signature"),
  aiEnabled: boolean("ai_enabled").notNull().default(true),
  personalAiEnabled: boolean("personal_ai_enabled").notNull().default(true),
  autoGenerateDrafts: boolean("auto_generate_drafts").notNull().default(true),
  enablePersonal: boolean("enable_personal").notNull().default(true),
  allowImageStorage: boolean("allow_image_storage").notNull().default(false),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export type UpsertUser = typeof users.$inferInsert;
export type User = typeof users.$inferSelect;
