import { sql } from "drizzle-orm";
import { pgTable, text, varchar, timestamp, boolean, real, jsonb, integer } from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  email: text("email").notNull().unique(),
  password: text("password").notNull(),
  name: text("name").notNull(),
  tone: text("tone").notNull().default('direct'),
  timezone: text("timezone").notNull().default('UTC'),
  defaultSignature: text("default_signature"),
  aiEnabled: boolean("ai_enabled").notNull().default(true),
  autoGenerateDrafts: boolean("auto_generate_drafts").notNull().default(true),
  enablePersonal: boolean("enable_personal").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const meetings = pgTable("meetings", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: 'cascade' }),
  title: text("title").notNull(),
  date: timestamp("date").notNull(),
  startTime: text("start_time"),
  duration: text("duration"),
  location: text("location"),
  rawNotes: text("raw_notes").notNull(),
  parseState: text("parse_state").notNull().default('draft'),
  summary: text("summary"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const attendees = pgTable("attendees", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  meetingId: varchar("meeting_id", { length: 36 }).notNull().references(() => meetings.id, { onDelete: 'cascade' }),
  name: text("name").notNull(),
  email: text("email"),
});

export const decisions = pgTable("decisions", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  meetingId: varchar("meeting_id", { length: 36 }).notNull().references(() => meetings.id, { onDelete: 'cascade' }),
  text: text("text").notNull(),
});

export const risks = pgTable("risks", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  meetingId: varchar("meeting_id", { length: 36 }).notNull().references(() => meetings.id, { onDelete: 'cascade' }),
  text: text("text").notNull(),
  severity: text("severity").notNull().default('medium'),
});

export const clarifyingQuestions = pgTable("clarifying_questions", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  meetingId: varchar("meeting_id", { length: 36 }).notNull().references(() => meetings.id, { onDelete: 'cascade' }),
  text: text("text").notNull(),
  options: text("options").array(),
  answer: text("answer"),
});

export const actionItems = pgTable("action_items", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  meetingId: varchar("meeting_id", { length: 36 }).notNull().references(() => meetings.id, { onDelete: 'cascade' }),
  text: text("text").notNull(),
  ownerName: text("owner_name"),
  ownerEmail: text("owner_email"),
  dueDate: timestamp("due_date"),
  status: text("status").notNull().default('needs_review'),
  confidenceOwner: real("confidence_owner").notNull().default(0),
  confidenceDueDate: real("confidence_due_date").notNull().default(0),
  tags: text("tags").array().notNull().default(sql`ARRAY[]::text[]`),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const followUpDrafts = pgTable("follow_up_drafts", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  meetingId: varchar("meeting_id", { length: 36 }).notNull().references(() => meetings.id, { onDelete: 'cascade' }),
  userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: 'cascade' }),
  type: text("type").notNull(),
  recipientName: text("recipient_name"),
  recipientEmail: text("recipient_email"),
  subject: text("subject").notNull(),
  body: text("body").notNull(),
  tone: text("tone").notNull(),
  state: text("state").notNull().default('generated'),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const personalEntries = pgTable("personal_entries", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: 'cascade' }),
  date: timestamp("date").notNull(),
  rawText: text("raw_text").notNull(),
  summary: text("summary"),
  top3: text("top3").array(),
  nextSteps: text("next_steps").array(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const insertUserSchema = createInsertSchema(users).omit({
  id: true,
  createdAt: true,
});

export const insertMeetingSchema = createInsertSchema(meetings).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertAttendeeSchema = createInsertSchema(attendees).omit({
  id: true,
});

export const insertDecisionSchema = createInsertSchema(decisions).omit({
  id: true,
});

export const insertRiskSchema = createInsertSchema(risks).omit({
  id: true,
});

export const insertClarifyingQuestionSchema = createInsertSchema(clarifyingQuestions).omit({
  id: true,
});

export const insertActionItemSchema = createInsertSchema(actionItems).omit({
  id: true,
  createdAt: true,
});

export const insertFollowUpDraftSchema = createInsertSchema(followUpDrafts).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertPersonalEntrySchema = createInsertSchema(personalEntries).omit({
  id: true,
  createdAt: true,
});

export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;

export type InsertMeeting = z.infer<typeof insertMeetingSchema>;
export type Meeting = typeof meetings.$inferSelect;

export type InsertAttendee = z.infer<typeof insertAttendeeSchema>;
export type Attendee = typeof attendees.$inferSelect;

export type InsertDecision = z.infer<typeof insertDecisionSchema>;
export type Decision = typeof decisions.$inferSelect;

export type InsertRisk = z.infer<typeof insertRiskSchema>;
export type Risk = typeof risks.$inferSelect;

export type InsertClarifyingQuestion = z.infer<typeof insertClarifyingQuestionSchema>;
export type ClarifyingQuestion = typeof clarifyingQuestions.$inferSelect;

export type InsertActionItem = z.infer<typeof insertActionItemSchema>;
export type ActionItem = typeof actionItems.$inferSelect;

export type InsertFollowUpDraft = z.infer<typeof insertFollowUpDraftSchema>;
export type FollowUpDraft = typeof followUpDrafts.$inferSelect;

export type InsertPersonalEntry = z.infer<typeof insertPersonalEntrySchema>;
export type PersonalEntry = typeof personalEntries.$inferSelect;
