import { sql } from "drizzle-orm";
import { pgTable, text, varchar, timestamp, boolean, real, jsonb, integer } from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod";

// ==================== USERS ====================
export const users = pgTable("users", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  email: text("email").notNull().unique(),
  password: text("password").notNull(),
  name: text("name").notNull(),
  tone: text("tone").notNull().default('direct'),
  timezone: text("timezone").notNull().default('UTC'),
  defaultSignature: text("default_signature"),
  aiEnabled: boolean("ai_enabled").notNull().default(true),
  autoGenerateDrafts: boolean("auto_generate_drafts").notNull().default(true),
  enablePersonal: boolean("enable_personal").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ==================== WORKSPACES (Phase 2) ====================
export const workspaces = pgTable("workspaces", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  createdByUserId: varchar("created_by_user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: 'cascade' }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const workspaceMembers = pgTable("workspace_members", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  workspaceId: varchar("workspace_id", { length: 36 }).notNull().references(() => workspaces.id, { onDelete: 'cascade' }),
  userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: 'cascade' }),
  role: text("role").notNull().default('member'), // owner, admin, member, viewer
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const workspaceInvites = pgTable("workspace_invites", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  workspaceId: varchar("workspace_id", { length: 36 }).notNull().references(() => workspaces.id, { onDelete: 'cascade' }),
  email: text("email").notNull(),
  token: text("token").notNull().unique(),
  role: text("role").notNull().default('member'),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  acceptedAt: timestamp("accepted_at"),
});

// ==================== OAUTH CONNECTIONS (Phase 2) ====================
export const oauthConnections = pgTable("oauth_connections", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: 'cascade' }),
  provider: text("provider").notNull(), // google, microsoft
  accountEmail: text("account_email").notNull(),
  accessToken: text("access_token").notNull(),
  refreshToken: text("refresh_token"),
  expiresAt: timestamp("expires_at"),
  scopes: text("scopes").array(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  lastUsedAt: timestamp("last_used_at"),
});

// ==================== CALENDAR EXPORTS (Phase 2) ====================
export const calendarExports = pgTable("calendar_exports", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: 'cascade' }),
  meetingId: varchar("meeting_id", { length: 36 }).references(() => meetings.id, { onDelete: 'set null' }),
  filename: text("filename").notNull(),
  contentHash: text("content_hash"),
  options: jsonb("options"), // { includeActionItems: boolean }
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ==================== AI AUDIT LOGS (Phase 2) ====================
export const aiAuditLogs = pgTable("ai_audit_logs", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: 'cascade' }),
  workspaceId: varchar("workspace_id", { length: 36 }).references(() => workspaces.id, { onDelete: 'set null' }),
  meetingId: varchar("meeting_id", { length: 36 }).references(() => meetings.id, { onDelete: 'set null' }),
  provider: text("provider").notNull(), // openai, google, mock
  model: text("model").notNull(),
  promptVersion: text("prompt_version"),
  inputHash: text("input_hash"),
  outputJson: jsonb("output_json"),
  validJson: boolean("valid_json").notNull().default(true),
  errorText: text("error_text"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ==================== MEETINGS ====================
export const meetings = pgTable("meetings", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: 'cascade' }),
  workspaceId: varchar("workspace_id", { length: 36 }).references(() => workspaces.id, { onDelete: 'set null' }),
  title: text("title").notNull(),
  date: timestamp("date").notNull(),
  startTime: text("start_time"),
  duration: text("duration"),
  location: text("location"),
  rawNotes: text("raw_notes").notNull(),
  parseState: text("parse_state").notNull().default('draft'),
  summary: text("summary"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const attendees = pgTable("attendees", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  meetingId: varchar("meeting_id", { length: 36 }).notNull().references(() => meetings.id, { onDelete: 'cascade' }),
  name: text("name").notNull(),
  email: text("email"),
});

export const decisions = pgTable("decisions", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  meetingId: varchar("meeting_id", { length: 36 }).notNull().references(() => meetings.id, { onDelete: 'cascade' }),
  text: text("text").notNull(),
});

export const risks = pgTable("risks", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  meetingId: varchar("meeting_id", { length: 36 }).notNull().references(() => meetings.id, { onDelete: 'cascade' }),
  text: text("text").notNull(),
  severity: text("severity").notNull().default('medium'),
});

export const clarifyingQuestions = pgTable("clarifying_questions", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  meetingId: varchar("meeting_id", { length: 36 }).notNull().references(() => meetings.id, { onDelete: 'cascade' }),
  text: text("text").notNull(),
  options: text("options").array(),
  answer: text("answer"),
});

// ==================== ACTION ITEMS ====================
export const actionItems = pgTable("action_items", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  meetingId: varchar("meeting_id", { length: 36 }).notNull().references(() => meetings.id, { onDelete: 'cascade' }),
  workspaceId: varchar("workspace_id", { length: 36 }).references(() => workspaces.id, { onDelete: 'set null' }),
  ownerUserId: varchar("owner_user_id", { length: 36 }).references(() => users.id, { onDelete: 'set null' }),
  text: text("text").notNull(),
  ownerName: text("owner_name"),
  ownerEmail: text("owner_email"),
  dueDate: timestamp("due_date"),
  status: text("status").notNull().default('needs_review'),
  confidenceOwner: real("confidence_owner").notNull().default(0),
  confidenceDueDate: real("confidence_due_date").notNull().default(0),
  tags: text("tags").array().notNull().default(sql`ARRAY[]::text[]`),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ==================== DRAFTS ====================
export const followUpDrafts = pgTable("follow_up_drafts", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  meetingId: varchar("meeting_id", { length: 36 }).notNull().references(() => meetings.id, { onDelete: 'cascade' }),
  userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: 'cascade' }),
  workspaceId: varchar("workspace_id", { length: 36 }).references(() => workspaces.id, { onDelete: 'set null' }),
  type: text("type").notNull(),
  recipientName: text("recipient_name"),
  recipientEmail: text("recipient_email"),
  subject: text("subject").notNull(),
  body: text("body").notNull(),
  tone: text("tone").notNull(),
  state: text("state").notNull().default('generated'),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// ==================== PERSONAL ENTRIES ====================
export const personalEntries = pgTable("personal_entries", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: 'cascade' }),
  date: timestamp("date").notNull(),
  rawText: text("raw_text").notNull(),
  summary: text("summary"),
  top3: text("top3").array(),
  nextSteps: text("next_steps").array(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ==================== INSERT SCHEMAS ====================
export const insertUserSchema = createInsertSchema(users).omit({
  id: true,
  createdAt: true,
});

export const insertWorkspaceSchema = createInsertSchema(workspaces).omit({
  id: true,
  createdAt: true,
});

export const insertWorkspaceMemberSchema = createInsertSchema(workspaceMembers).omit({
  id: true,
  createdAt: true,
});

export const insertWorkspaceInviteSchema = createInsertSchema(workspaceInvites).omit({
  id: true,
  createdAt: true,
  acceptedAt: true,
});

export const insertOAuthConnectionSchema = createInsertSchema(oauthConnections).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  lastUsedAt: true,
});

export const insertCalendarExportSchema = createInsertSchema(calendarExports).omit({
  id: true,
  createdAt: true,
});

export const insertAiAuditLogSchema = createInsertSchema(aiAuditLogs).omit({
  id: true,
  createdAt: true,
});

export const insertMeetingSchema = createInsertSchema(meetings).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertAttendeeSchema = createInsertSchema(attendees).omit({
  id: true,
});

export const insertDecisionSchema = createInsertSchema(decisions).omit({
  id: true,
});

export const insertRiskSchema = createInsertSchema(risks).omit({
  id: true,
});

export const insertClarifyingQuestionSchema = createInsertSchema(clarifyingQuestions).omit({
  id: true,
});

export const insertActionItemSchema = createInsertSchema(actionItems).omit({
  id: true,
  createdAt: true,
});

export const insertFollowUpDraftSchema = createInsertSchema(followUpDrafts).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const insertPersonalEntrySchema = createInsertSchema(personalEntries).omit({
  id: true,
  createdAt: true,
});

// ==================== TYPES ====================
export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;

export type InsertWorkspace = z.infer<typeof insertWorkspaceSchema>;
export type Workspace = typeof workspaces.$inferSelect;

export type InsertWorkspaceMember = z.infer<typeof insertWorkspaceMemberSchema>;
export type WorkspaceMember = typeof workspaceMembers.$inferSelect;

export type InsertWorkspaceInvite = z.infer<typeof insertWorkspaceInviteSchema>;
export type WorkspaceInvite = typeof workspaceInvites.$inferSelect;

export type InsertOAuthConnection = z.infer<typeof insertOAuthConnectionSchema>;
export type OAuthConnection = typeof oauthConnections.$inferSelect;

export type InsertCalendarExport = z.infer<typeof insertCalendarExportSchema>;
export type CalendarExport = typeof calendarExports.$inferSelect;

export type InsertAiAuditLog = z.infer<typeof insertAiAuditLogSchema>;
export type AiAuditLog = typeof aiAuditLogs.$inferSelect;

export type InsertMeeting = z.infer<typeof insertMeetingSchema>;
export type Meeting = typeof meetings.$inferSelect;

export type InsertAttendee = z.infer<typeof insertAttendeeSchema>;
export type Attendee = typeof attendees.$inferSelect;

export type InsertDecision = z.infer<typeof insertDecisionSchema>;
export type Decision = typeof decisions.$inferSelect;

export type InsertRisk = z.infer<typeof insertRiskSchema>;
export type Risk = typeof risks.$inferSelect;

export type InsertClarifyingQuestion = z.infer<typeof insertClarifyingQuestionSchema>;
export type ClarifyingQuestion = typeof clarifyingQuestions.$inferSelect;

export type InsertActionItem = z.infer<typeof insertActionItemSchema>;
export type ActionItem = typeof actionItems.$inferSelect;

export type InsertFollowUpDraft = z.infer<typeof insertFollowUpDraftSchema>;
export type FollowUpDraft = typeof followUpDrafts.$inferSelect;

export type InsertPersonalEntry = z.infer<typeof insertPersonalEntrySchema>;
export type PersonalEntry = typeof personalEntries.$inferSelect;

// ==================== ROLE TYPES ====================
export type WorkspaceRole = 'owner' | 'admin' | 'member' | 'viewer';
export type OAuthProvider = 'google' | 'microsoft';
